<a href="https://colab.research.google.com/github/Yiting-Wang98/MSSP607/blob/main/assignments/week%204/week%204%20assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)


from google.colab import userdata
github_token = userdata.get('Gitkey')
owner = 'Yiting-Wang98'          # Replace with the GitHub repo owner
repository = 'MSSP607'     # Replace with the GitHub repo name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

CompletedProcess(args=['git', 'clone', 'https://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@github.com/Yiting-Wang98/MSSP607.git'], returncode=128)

In [4]:
import pandas as pd
data = pd.read_csv('/content/MSSP607/data/week4/parsed (1).csv')

In [5]:
# a. Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'
japan=data[data["place"].str.contains("Japan", na=False)]
japan_mb=japan[japan['magType']=='mb']
japan_mb["mag"].quantile(0.95)

np.float64(4.9)

In [6]:
#b. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.
Indonesia=data[data['place'].str.contains('Indonesia',na=False)]
Indonesia_tsunamis=Indonesia[Indonesia['tsunami']==1]
Percentage=len(Indonesia_tsunamis)/len(Indonesia)*100
print(Percentage)

23.12925170068027

In [7]:
#c. Get summary statistics for earthquakes in Nevada
Nevada=data[data['place'].str.contains('Nevada',na=False)]
Nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.00,677.00,15.00,677.00,677.00,1.00,677.00,677.00,677.00,677.00,677.00,677.00,677.00
mean,2.44,0.17,2.40,154.03,0.49,2.84,12.61,0.15,10.69,1538314029955.64,0.00,-480.00,1538402209729.79
std,0.50,0.17,4.63,68.77,0.69,NaN,9.89,0.08,19.25,595407023.31,0.00,0.00,600026653.10
min,2.00,0.00,1.00,29.14,-0.50,2.84,3.00,0.00,0.00,1537247268525.00,0.00,-480.00,1537306663881.00
25%,2.00,0.05,1.00,97.67,-0.10,2.84,6.00,0.11,0.00,1537854384162.00,0.00,-480.00,1537927505348.00
50%,2.20,0.11,1.00,149.55,0.40,2.84,9.00,0.15,2.00,1538279862199.00,0.00,-480.00,1538427614580.00
75%,2.90,0.23,1.00,200.47,0.90,2.84,16.00,0.19,12.00,1538821434704.00,0.00,-480.00,1538877980517.00
max,3.30,1.41,19.00,355.91,2.90,2.84,61.00,0.86,129.00,1539461038285.00,0.00,-480.00,1539482718719.00

In [8]:
#d. Add a column to the dataframe indicating whether or not the earthquake happened
#in a country or US state that is on the Ring of Fire.
#Use Bolivia, Chile, Ecuador, Peru, Costa Rica, Guatemala, Mexico (be sure not to select New Mexico),
#Japan, Philippines, Indonesia, New Zealand, Antarctica (look for the Antarctic), Canada, Fiji, Alaska, Washington,
# California, Russia, Taiwan, Tonga, and the Kermadec Islands).
data['ring_of_fire'] = data.parsed_place.str.contains(r'|'.join([
    'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
    'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
    'New Zealand', 'Antarctic', 'Canada', 'Fiji',
    'Alaska', 'Washington', 'California', 'Russia',
    'Taiwan', 'Tonga', 'Kermadec Islands'
]))

data[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [9]:
#e. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them,
filtered_data = data[(data['ring_of_fire'] == True) & (data['type'] == 'earthquake')]
total_inside = data[(data['ring_of_fire'] == True) & (data['type'] == 'earthquake')].type.count()
total_outside = data[(data['ring_of_fire'] == False) & (data['type'] == 'earthquake')].type.count()
print('The total number of earthquakes in the Ring of Fire is: ', total_inside)
print('The total number of earthquakes outside the Ring of Fire is: ', total_outside)

The total number of earthquakes in the Ring of Fire is:  7004
The total number of earthquakes outside the Ring of Fire is:  2077

In [10]:
#f. Find the tsunami count along the Ring of Fire.
ring_of_fire_data = data[
    data["ring_of_fire"]
]

ring_of_fire_data["tsunami"].sum()

np.int64(45)