<a href="https://colab.research.google.com/github/Yiting-Wang98/MSSP607/blob/main/assignments/week%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/MSSP607/Codesamples/parsed.csv')

In [3]:
# a. Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'
japan=data[data["place"].str.contains("Japan", na=False)]
japan_mb=japan[japan['magType']=='mb']
japan_mb["mag"].quantile(0.95)

np.float64(4.9)

In [4]:
#b. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.
Indonesia=data[data['place'].str.contains('Indonesia',na=False)]
Indonesia_tsunamis=Indonesia[Indonesia['tsunami']==1]
Percentage=len(Indonesia_tsunamis)/len(Indonesia)*100
print(Percentage)

23.12925170068027

In [5]:
#c. Get summary statistics for earthquakes in Nevada
Nevada=data[data['place'].str.contains('Nevada',na=False)]
Nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,677.000000,15.000000,677.000000,677.000000,1.00,677.000000,677.000000,677.000000,6.770000e+02,677.0,677.0,6.770000e+02
mean,2.440000,0.166982,2.400000,154.029527,0.491728,2.84,12.608567,0.151909,10.688331,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166400,4.626013,68.769713,0.689560,NaN,9.890620,0.084742,19.252727,5.954070e+08,0.0,0.0,6.000267e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.054000,1.000000,97.670000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.113000,1.000000,149.550000,0.400000,2.84,9.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.234000,1.000000,200.470000,0.900000,2.84,16.000000,0.186700,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [6]:
#d. Add a column to the dataframe indicating whether or not the earthquake happened
#in a country or US state that is on the Ring of Fire.
#Use Bolivia, Chile, Ecuador, Peru, Costa Rica, Guatemala, Mexico (be sure not to select New Mexico),
#Japan, Philippines, Indonesia, New Zealand, Antarctica (look for the Antarctic), Canada, Fiji, Alaska, Washington,
# California, Russia, Taiwan, Tonga, and the Kermadec Islands).
data['ring_of_fire'] = data.parsed_place.str.contains(r'|'.join([
    'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
    'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
    'New Zealand', 'Antarctic', 'Canada', 'Fiji',
    'Alaska', 'Washington', 'California', 'Russia',
    'Taiwan', 'Tonga', 'Kermadec Islands'
]))

data[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [7]:
#e. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them,
filtered_data = data[(data['ring_of_fire'] == True) & (data['type'] == 'earthquake')]
total_inside = data[(data['ring_of_fire'] == True) & (data['type'] == 'earthquake')].type.count()
total_outside = data[(data['ring_of_fire'] == False) & (data['type'] == 'earthquake')].type.count()
print('The total number of earthquakes in the Ring of Fire is: ', total_inside)
print('The total number of earthquakes outside the Ring of Fire is: ', total_outside)

The total number of earthquakes in the Ring of Fire is:  7004
The total number of earthquakes outside the Ring of Fire is:  2077

In [8]:
#f. Find the tsunami count along the Ring of Fire.
ring_of_fire_data = data[
    data["ring_of_fire"]
]

ring_of_fire_data["tsunami"].sum()

np.int64(45)