In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os

github_token = userdata.get('Gitkey')
owner = 'Yiting-Wang98'          # Replace with the GitHub repo owner
repository = 'MSSP607'     # Replace with the GitHub repo name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

CompletedProcess(args=['git', 'clone', 'https://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@github.com/Yiting-Wang98/MSSP607.git'], returncode=0)

In [8]:
import pandas as pd
df = pd.read_csv("/content/MSSP607/data/week 6/Student Performance Data (1).csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [11]:
passed_students = lambda df: df[df["math score"] >= 60][
    ["lunch", "gender", "race/ethnicity", "parental level of education", "reading score", "writing score",
     "total score", "test preparation course",'admission prospect']]
result = passed_students(df)
print(type(result))
result.head()

<class 'pandas.core.frame.DataFrame'>

,lunch,gender,race/ethnicity,parental level of education,reading score,writing score,total score,test preparation course,admission prospect
0,standard,female,group B,bachelor's degree,72,74,218,none,medium
1,standard,female,group C,some college,90,88,247,completed,high
2,standard,female,group B,master's degree,95,93,278,none,high
4,standard,male,group C,some college,78,75,229,none,high
5,standard,female,group B,associate's degree,83,78,232,none,high