<a href="https://colab.research.google.com/github/Yiting-Wang98/MSSP607/blob/main/assignments/week%205/week%205%20assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

b.read each file into a dataframe

In [2]:
import pandas as pd
aapl = pd.read_csv("/content/drive/MyDrive/MSSP607/Codesamples/week 5dataset/aapl (1).csv")
amzn = pd.read_csv("/content/drive/MyDrive/MSSP607/Codesamples/week 5dataset/amzn.csv")
nflx = pd.read_csv("/content/drive/MyDrive/MSSP607/Codesamples/week 5dataset/nflx.csv")
fb = pd.read_csv("/content/drive/MyDrive/MSSP607/Codesamples/week 5dataset/fb.csv")
goog = pd.read_csv("/content/drive/MyDrive/MSSP607/Codesamples/week 5dataset/goog.csv")

In [3]:
aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [4]:
amzn.head()

         date     open     high      low    close   volume
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475

In [5]:
nflx.head()

         date    open    high       low   close    volume
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178

In [6]:
fb.head()

         date    open    high       low   close    volume
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726

In [7]:
goog.head()

         date     open     high      low    close   volume
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603

c.add ticker

In [10]:
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
nflx["ticker"] = "NFLX"
fb["ticker"] = "FB"
goog["ticker"] = "GOOG"

d.append each file together into a single dataframe + e.save the results in a cvs file called faanf.csv

In [13]:
faanf=pd.concat([aapl,amzn,nflx,fb,goog],ignore_index=True)

pd.concat()合并
ignore_index=true
合并之后生成重复连续的index

In [14]:
faanf.to_csv("faanf.csv", index=False)

In [15]:
!ls

drive  faanf.csv  sample_data

f. Using 'fanng.csv', use type conversion to change the 'date' column into a 'datetime' and the 'volume' column into integers.  Then sort by 'date' and 'ticker.'

In [17]:
faanf = pd.read_csv("faanf.csv")
faanf['date']=pd.to_datetime(faanf['date'])

In [19]:
faanf['volume']=faanf['volume'].astype(int)
faanf.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [20]:
faanf=faanf.sort_values(['date','ticker'])

g. Find the seven rows within the highest value for volume

In [21]:
faanf.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
895 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
806 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
810 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
807 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

h. Use the melt() method to make the 'date' and 'ticker' key identifiers.  Melt the remaining columns so that there are not separated.

In [23]:
melted = faanf.melt(
    id_vars=["date", "ticker"])
melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000