<a href="https://colab.research.google.com/github/Yiting-Wang98/MSSP607/blob/main/assignments/week%205/week_5_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os
import subprocess

github_token = userdata.get('Git_Key') #Retrieve secret key for user
owner = 'Yiting-Wang98' # Replace with the GitHub repository owner
repository = 'MSSP607' # Replace with the GitHub repository name

clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

#!git clone https://github.com/"owner"/"repository".git for public repositories

Changed directory to: /content/MSSP607/MSSP607

In [20]:
#b.read each file into a dataframe

In [21]:
import pandas as pd
aapl = pd.read_csv("/content/MSSP607/data/week 6/week 5/aapl (2).csv")
amzn = pd.read_csv("/content/MSSP607/data/week 6/week 5/amzn (1).csv")
nflx = pd.read_csv("/content/MSSP607/data/week 6/week 5/nflx (1).csv")
fb = pd.read_csv("/content/MSSP607/data/week 6/week 5/fb (1).csv")
goog = pd.read_csv("/content/MSSP607/data/week 6/week 5/goog (1).csv")

In [22]:
aapl.head()

         date   open   high    low  close    volume
0  2018-01-02 166.93 169.03 166.04 168.99  25555934
1  2018-01-03 169.25 171.23 168.69 168.96  29517899
2  2018-01-04 169.26 170.17 168.81 169.74  22434597
3  2018-01-05 170.14 172.04 169.76 171.68  23660018
4  2018-01-08 171.04 172.27 170.63 171.04  20567766

In [23]:
amzn.head()

         date    open    high     low   close   volume
0  2018-01-02 1172.00 1190.00 1170.51 1189.01  2694494
1  2018-01-03 1188.30 1205.49 1188.30 1204.20  3108793
2  2018-01-04 1205.00 1215.87 1204.66 1209.59  3022089
3  2018-01-05 1217.51 1229.14 1210.00 1229.14  3544743
4  2018-01-08 1236.00 1253.08 1232.03 1246.87  4279475

In [24]:
nflx.head()

         date   open   high    low  close    volume
0  2018-01-02 196.10 201.65 195.42 201.07  10966889
1  2018-01-03 202.05 206.21 201.50 205.05   8591369
2  2018-01-04 206.20 207.05 204.00 205.63   6029616
3  2018-01-05 207.25 210.02 205.59 209.99   7033240
4  2018-01-08 210.02 212.50 208.44 212.05   5580178

In [25]:
fb.head()

         date   open   high    low  close    volume
0  2018-01-02 177.68 181.58 177.55 181.42  18151903
1  2018-01-03 181.88 184.78 181.33 184.67  16886563
2  2018-01-04 184.90 186.21 184.10 184.33  13880896
3  2018-01-05 185.59 186.90 184.93 186.85  13574535
4  2018-01-08 187.20 188.90 186.33 188.28  17994726

In [26]:
goog.head()

         date    open    high     low   close   volume
0  2018-01-02 1048.34 1066.94 1045.23 1065.00  1237564
1  2018-01-03 1064.31 1086.29 1063.21 1082.48  1430170
2  2018-01-04 1088.00 1093.57 1084.00 1086.40  1004605
3  2018-01-05 1094.00 1104.25 1092.00 1102.23  1279123
4  2018-01-08 1102.23 1111.27 1101.62 1106.94  1047603

c.add ticker

In [27]:
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
nflx["ticker"] = "NFLX"
fb["ticker"] = "FB"
goog["ticker"] = "GOOG"

d.append each file together into a single dataframe + e.save the results in a cvs file called faanf.csv

In [28]:
faanf=pd.concat([aapl,amzn,nflx,fb,goog],ignore_index=True)

In [29]:
display(faanf)

            date    open    high     low   close    volume ticker
0     2018-01-02  166.93  169.03  166.04  168.99  25555934   AAPL
1     2018-01-03  169.25  171.23  168.69  168.96  29517899   AAPL
2     2018-01-04  169.26  170.17  168.81  169.74  22434597   AAPL
3     2018-01-05  170.14  172.04  169.76  171.68  23660018   AAPL
4     2018-01-08  171.04  172.27  170.63  171.04  20567766   AAPL
...          ...     ...     ...     ...     ...       ...    ...
1250  2018-12-24  973.90 1003.54  970.11  976.22   1590328   GOOG
1251  2018-12-26  989.01 1040.00  983.00 1039.46   2373270   GOOG
1252  2018-12-27 1017.15 1043.89  997.00 1043.88   2109777   GOOG
1253  2018-12-28 1049.62 1055.56 1033.10 1037.08   1413772   GOOG
1254  2018-12-31 1050.96 1052.70 1023.59 1035.61   1493722   GOOG

[1255 rows x 7 columns]

In [30]:
faanf.to_csv("faanf.csv", index=False)

f. Using 'fanng.csv', use type conversion to change the 'date' column into a 'datetime' and the 'volume' column into integers. Then sort by 'date' and 'ticker.'

In [31]:
faanf = pd.read_csv("faanf.csv")
faanf['date']=pd.to_datetime(faanf['date'])

In [32]:
faanf['volume']=faanf['volume'].astype(int)
faanf.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [33]:
faanf=faanf.sort_values(['date','ticker'])

g. Find the seven rows within the highest value for volume

In [34]:
faanf.nlargest(7, "volume")

          date   open   high    low  close     volume ticker
895 2018-07-26 174.89 180.13 173.75 176.26  169803668     FB
806 2018-03-20 167.47 170.20 161.95 168.15  129851768     FB
810 2018-03-26 160.82 161.10 149.02 160.06  126116634     FB
807 2018-03-21 164.80 173.40 163.30 169.39  106598834     FB
182 2018-09-21 219.07 219.65 215.61 215.98   96246748   AAPL
245 2018-12-21 156.19 157.48 148.99 150.09   95744384   AAPL
212 2018-11-02 207.93 212.00 203.84 205.88   91328654   AAPL

h. Use the melt() method to make the 'date' and 'ticker' key identifiers. Melt the remaining columns so that there are not separated.

In [35]:
faanf.melt(id_vars=["date", "ticker"])

           date ticker variable       value
0    2018-01-02   AAPL     open      166.93
1    2018-01-02   AMZN     open     1172.00
2    2018-01-02     FB     open      177.68
3    2018-01-02   GOOG     open     1048.34
4    2018-01-02   NFLX     open      196.10
...         ...    ...      ...         ...
6270 2018-12-31   AAPL   volume 35003466.00
6271 2018-12-31   AMZN   volume  6954507.00
6272 2018-12-31     FB   volume 24625308.00
6273 2018-12-31   GOOG   volume  1493722.00
6274 2018-12-31   NFLX   volume 13508920.00

[6275 rows x 4 columns]